version: "3.9"

services:
  app:
    build: .
    container_name: rockets_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7.4
    container_name: rockets_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: